import Nav from './components/Nav'
import Provider from './components/Provider'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Nav />
          <main className="pt-16">{children}</main>
        </Provider>
      </body>
    </html>
  )
}
