'use client'

import Nav from './components/Nav'
import Provider from './components/Provider'
import './globals.css'
import { LoadingBarProvider } from './store/loading-bar'
import { FiltersContextProvider } from './store/filters'
import { PostCarContextProvider } from './store/post-car'
import { SearchContextProvider } from './store/search-car'
import Footer from './components/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <PostCarContextProvider>
          <LoadingBarProvider>
            <SearchContextProvider>
              <FiltersContextProvider>
                <Provider>
                  <Nav />
                  <main className="pt-16">{children}</main>
                  <Footer />
                </Provider>
              </FiltersContextProvider>
            </SearchContextProvider>
          </LoadingBarProvider>
        </PostCarContextProvider>
      </body>
    </html>
  )
}
